// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestionInterfaceTry101.Server.Data;

#nullable disable

namespace QuestionInterfaceTry101.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestionInterfaceTry101.Server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuestionInterfaceTry101.Server.Model.WorksheetModel", b =>
                {
                    b.Property<int>("WorksheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorksheetType")
                        .HasColumnType("TEXT");

                    b.HasKey("WorksheetId");

                    b.ToTable("Worksheets");
                });

            modelBuilder.Entity("QuestionInterfaceTry101.Server.Model.qusModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfOptions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sct")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorksheetModelWorksheetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("WorksheetModelWorksheetId");

                    b.ToTable("qus", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuestionInterfaceTry101.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuestionInterfaceTry101.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestionInterfaceTry101.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuestionInterfaceTry101.Server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionInterfaceTry101.Server.Model.WorksheetModel", b =>
                {
                    b.OwnsOne("QuestionInterfaceTry101.Server.Model.FinalMessageModel", "FinalMessage", b1 =>
                        {
                            b1.Property<int>("WorksheetModelWorksheetId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.HasKey("WorksheetModelWorksheetId");

                            b1.ToTable("Worksheets");

                            b1.WithOwner()
                                .HasForeignKey("WorksheetModelWorksheetId");

                            b1.OwnsOne("QuestionInterfaceTry101.Server.Model.ConfigModel", "Config", b2 =>
                                {
                                    b2.Property<int>("FinalMessageModelWorksheetModelWorksheetId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Style")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Styledegree")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("FinalMessageModelWorksheetModelWorksheetId");

                                    b2.ToTable("Worksheets");

                                    b2.WithOwner()
                                        .HasForeignKey("FinalMessageModelWorksheetModelWorksheetId");
                                });

                            b1.Navigation("Config")
                                .IsRequired();
                        });

                    b.OwnsOne("QuestionInterfaceTry101.Server.Model.TitleModel", "Title", b1 =>
                        {
                            b1.Property<int>("WorksheetModelWorksheetId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.HasKey("WorksheetModelWorksheetId");

                            b1.ToTable("Worksheets");

                            b1.WithOwner()
                                .HasForeignKey("WorksheetModelWorksheetId");

                            b1.OwnsOne("QuestionInterfaceTry101.Server.Model.ConfigModel", "Config", b2 =>
                                {
                                    b2.Property<int>("TitleModelWorksheetModelWorksheetId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Style")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Styledegree")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TitleModelWorksheetModelWorksheetId");

                                    b2.ToTable("Worksheets");

                                    b2.WithOwner()
                                        .HasForeignKey("TitleModelWorksheetModelWorksheetId");
                                });

                            b1.Navigation("Config")
                                .IsRequired();
                        });

                    b.Navigation("FinalMessage")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionInterfaceTry101.Server.Model.qusModel", b =>
                {
                    b.HasOne("QuestionInterfaceTry101.Server.Model.WorksheetModel", null)
                        .WithMany("qus")
                        .HasForeignKey("WorksheetModelWorksheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("QuestionInterfaceTry101.Server.Model.SettingsModel", "Settings", b1 =>
                        {
                            b1.Property<int>("qusModelid")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Number1")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Number2")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Operation")
                                .HasColumnType("TEXT");

                            b1.HasKey("qusModelid");

                            b1.ToTable("qus");

                            b1.WithOwner()
                                .HasForeignKey("qusModelid");
                        });

                    b.OwnsOne("QuestionInterfaceTry101.Server.Model.TitleModel", "Title", b1 =>
                        {
                            b1.Property<int>("qusModelid")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Text")
                                .HasColumnType("TEXT");

                            b1.HasKey("qusModelid");

                            b1.ToTable("qus");

                            b1.WithOwner()
                                .HasForeignKey("qusModelid");

                            b1.OwnsOne("QuestionInterfaceTry101.Server.Model.ConfigModel", "Config", b2 =>
                                {
                                    b2.Property<int>("TitleModelqusModelid")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Style")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Styledegree")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TitleModelqusModelid");

                                    b2.ToTable("qus");

                                    b2.WithOwner()
                                        .HasForeignKey("TitleModelqusModelid");
                                });

                            b1.Navigation("Config")
                                .IsRequired();
                        });

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionInterfaceTry101.Server.Model.WorksheetModel", b =>
                {
                    b.Navigation("qus");
                });
#pragma warning restore 612, 618
        }
    }
}
